In [1]:
import pandas as pd

In [2]:
# !pip install scikit-learn

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [4]:
# from sklearn.datasets import load_iris

In [5]:
df= pd.read_csv('diabetes.csv')
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [6]:
from sklearn.preprocessing import LabelEncoder

encoder= LabelEncoder()

In [7]:
df.gender= encoder.fit_transform(df.gender)
# Female -0, Male-1 
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,0,80.0,0,1,never,25.19,6.6,140,0
1,0,54.0,0,0,No Info,27.32,6.6,80,0
2,1,28.0,0,0,never,27.32,5.7,158,0
3,0,36.0,0,0,current,23.45,5.0,155,0
4,1,76.0,1,1,current,20.14,4.8,155,0

In [8]:
df.smoking_history.value_counts()
#No Info        0
# never          4
# former         3
# current         1
#  not current     5
# ever            2

smoking_history
No Info        35816
never          35095
former          9352
current         9286
not current     6447
ever            4004
Name: count, dtype: int64

In [9]:
df.smoking_history= encoder.fit_transform(df.smoking_history)

In [10]:
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,0,80.0,0,1,4,25.19,6.6,140,0
1,0,54.0,0,0,0,27.32,6.6,80,0
2,1,28.0,0,0,4,27.32,5.7,158,0
3,0,36.0,0,0,1,23.45,5.0,155,0
4,1,76.0,1,1,1,20.14,4.8,155,0

In [11]:
df.smoking_history.value_counts()

smoking_history
0    35816
4    35095
3     9352
1     9286
5     6447
2     4004
Name: count, dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  int32
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  int32
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int32(2), int64(4)
memory usage: 6.1 MB

In [13]:
df.shape

(100000, 9)

In [14]:
df.diabetes.value_counts()

diabetes
0    91500
1     8500
Name: count, dtype: int64

In [15]:
df_new= df[df.diabetes==0].sample(n=8500,ignore_index=True, random_state=10)
df_new

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,1,64.0,0,0,4,39.17,6.0,80,0
1,0,16.0,0,0,0,21.49,6.2,90,0
2,0,53.0,0,0,4,29.40,3.5,160,0
3,1,61.0,1,0,4,27.32,6.2,145,0
4,0,55.0,0,0,4,40.73,4.8,80,0
...,...,...,...,...,...,...,...,...,...
8495,1,38.0,0,0,4,24.84,6.5,100,0
8496,0,19.0,0,0,0,18.87,5.7,145,0
8497,0,37.0,0,0,1,38.00,4.8,200,0
8498,1,48.0,1,0,0,26.53,5.0,80,0
8499,0,69.0,0,0,0,27.32,6.6,159,0

In [16]:
df_new_1= df[df.diabetes==1]
df_new_1

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
6,0,44.0,0,0,4,19.31,6.5,200,1
26,1,67.0,0,1,5,27.32,6.5,200,1
38,1,50.0,1,0,1,27.32,5.7,260,1
40,1,73.0,0,0,3,25.91,9.0,160,1
53,0,53.0,0,0,3,27.32,7.0,159,1
...,...,...,...,...,...,...,...,...,...
99935,0,65.0,1,1,4,33.55,8.2,140,1
99938,1,55.0,0,1,3,30.42,6.2,300,1
99957,0,61.0,0,0,0,34.45,6.5,280,1
99962,0,58.0,1,0,4,38.31,7.0,200,1
99979,0,61.0,0,0,1,30.11,6.2,240,1

In [17]:
final_df= pd.concat((df_new,df_new_1),ignore_index=True)
final_df

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,1,64.0,0,0,4,39.17,6.0,80,0
1,0,16.0,0,0,0,21.49,6.2,90,0
2,0,53.0,0,0,4,29.40,3.5,160,0
3,1,61.0,1,0,4,27.32,6.2,145,0
4,0,55.0,0,0,4,40.73,4.8,80,0
...,...,...,...,...,...,...,...,...,...
16995,0,65.0,1,1,4,33.55,8.2,140,1
16996,1,55.0,0,1,3,30.42,6.2,300,1
16997,0,61.0,0,0,0,34.45,6.5,280,1
16998,0,58.0,1,0,4,38.31,7.0,200,1
16999,0,61.0,0,0,1,30.11,6.2,240,1

In [18]:
#independent and dependent variables
x=final_df.iloc[:,:-1]
x

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level
0,1,64.0,0,0,4,39.17,6.0,80
1,0,16.0,0,0,0,21.49,6.2,90
2,0,53.0,0,0,4,29.40,3.5,160
3,1,61.0,1,0,4,27.32,6.2,145
4,0,55.0,0,0,4,40.73,4.8,80
...,...,...,...,...,...,...,...,...
16995,0,65.0,1,1,4,33.55,8.2,140
16996,1,55.0,0,1,3,30.42,6.2,300
16997,0,61.0,0,0,0,34.45,6.5,280
16998,0,58.0,1,0,4,38.31,7.0,200
16999,0,61.0,0,0,1,30.11,6.2,240

In [19]:
y=final_df.iloc[:,-1]

In [20]:
y

0        0
1        0
2        0
3        0
4        0
        ..
16995    1
16996    1
16997    1
16998    1
16999    1
Name: diabetes, Length: 17000, dtype: int64

In [21]:
x_train,x_test, y_train,y_test= train_test_split(x,y,test_size=0.30,random_state=50)

In [22]:
x_train

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level
16288,1,40.0,0,0,4,31.34,7.5,160
9877,1,57.0,0,0,4,32.32,6.2,300
8191,0,38.0,0,0,1,31.43,6.0,85
9830,1,69.0,0,0,2,24.48,8.2,200
16544,1,40.0,1,0,0,28.81,6.6,130
...,...,...,...,...,...,...,...,...
14565,0,58.0,0,0,0,26.72,7.0,130
15649,1,77.0,0,0,4,26.15,6.1,260
10123,0,80.0,0,1,3,24.50,6.2,280
5600,1,35.0,0,0,4,30.69,6.1,155
14000,0,53.0,0,0,0,27.32,6.0,300

In [23]:
y_train

16288    1
9877     1
8191     0
9830     1
16544    1
        ..
14565    1
15649    1
10123    1
5600     0
14000    1
Name: diabetes, Length: 11900, dtype: int64

In [24]:
from sklearn.tree import DecisionTreeClassifier

In [25]:
from sklearn.model_selection import GridSearchCV

In [26]:
new_model= DecisionTreeClassifier()

In [27]:
params={
    'criterion':['gini','entropy'],
    'max_depth':[1,2,3,4,5,6,7,8,9,10,11,12,13]
}

In [28]:
cv= GridSearchCV(new_model,param_grid=params, scoring='accuracy')

In [29]:
cv.fit(x_train,y_train)

GridSearchCV(estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                       13]},
             scoring='accuracy')

In [30]:
cv.best_params_

{'criterion': 'entropy', 'max_depth': 8}

In [31]:
model= DecisionTreeClassifier(criterion='entropy',max_depth=8)

In [32]:
model.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=8)

In [33]:
y_pred= model.predict(x_test)

In [34]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.86      0.90      2574
           1       0.87      0.95      0.91      2526

    accuracy                           0.90      5100
   macro avg       0.91      0.90      0.90      5100
weighted avg       0.91      0.90      0.90      5100

In [35]:
accuracy_score(y_test,y_pred)

0.9043137254901961

In [36]:
import joblib

In [37]:
joblib.dump(model,'diabetes.pkl')

['diabetes.pkl']

In [38]:
df.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes'],
      dtype='object')